### PR TITLE
Bass boost command

### PR DESCRIPTION
**Pull request by CodeFromCirc**
You have been waiting for this....
*A bass boost command*. Yes, you heard right, a *bass boost* command. Listen to your trap music all you want, with the bass boost command. List of presets: `off`, `low`, `medium`, `high`, and `insane`. ~~Thank me later.~~

### CODE REVIEW

**Comment by Devoxin** [comment]
Totally not ripped from JukeBot's source... :/

**Comment by natanbc** [comment]
stoler

**Comment by Stylite** [comment]
steal

**Comment by Devoxin** [comment]
Just gonna reference source...
https://github.com/Devoxin/JukeBot/blob/master/src/main/java/jukebot/audioutilities/AudioHandler.java#L180

https://github.com/Devoxin/JukeBot/blob/master/src/main/java/jukebot/commands/BassBoost.java

**Comment by CodeFromCirc** [comment]
it's been called off

**Pull request closed without merging**
